/**
 * Decide how to install and start a project generated by bolt.diy.
 * The image runs that project on a real Linux host. WebContainer remains
 * the in-browser runtime; this planner only covers the container path.
 */

const LOCKFILES = ['pnpm-lock.yaml', 'pnpm-workspace.yaml', 'yarn.lock', 'package-lock.json', 'bun.lock', 'bun.lockb'];

/**
 * @param {Record<string, string> | undefined} dependencies
 * @param {Record<string, string> | undefined} devDependencies
 */
function dependencyNames(dependencies, devDependencies) {
  return new Set([...Object.keys(dependencies || {}), ...Object.keys(devDependencies || {})]);
}

/**
 * @param {string | undefined} packageManager
 */
function packageManagerName(packageManager) {
  if (!packageManager || typeof packageManager !== 'string') {
    return '';
  }

  return packageManager.split('@')[0];
}

/**
 * @param {Set<string>} deps
 * @param {string} scriptBody
 */
function bindArgs(deps, scriptBody, port) {
  const has = (name) => deps.has(name);

  if (has('next')) {
    return ['-H', '0.0.0.0', '-p', port];
  }

  if (
    has('vite') ||
    has('astro') ||
    has('@sveltejs/kit') ||
    has('nuxt') ||
    has('@builder.io/qwik') ||
    has('@remix-run/dev') ||
    has('@react-router/dev') ||
    /\bvite\b/.test(scriptBody)
  ) {
    return ['--host', '0.0.0.0', '--port', port];
  }

  if (has('@angular/cli') || has('@angular/core') || /\bng\s+serve\b/.test(scriptBody)) {
    return ['--host', '0.0.0.0', '--port', port];
  }

  if (has('expo') || /\bexpo\s+start\b/.test(scriptBody)) {
    return ['--host', 'lan', '--port', port];
  }

  if (has('@slidev/cli') || /\bslidev\b/.test(scriptBody)) {
    return ['--remote', '--port', port];
  }

  return [];
}

/**
 * @param {'pnpm' | 'yarn' | 'npm'} manager
 * @param {string[]} lockfiles
 */
function installCommands(manager, lockfiles) {
  const has = (name) => lockfiles.includes(name);

  if (manager === 'pnpm') {
    if (has('pnpm-lock.yaml')) {
      return {
        install: ['pnpm', 'install', '--frozen-lockfile'],
        installFallback: ['pnpm', 'install', '--no-frozen-lockfile'],
      };
    }

    return { install: ['pnpm', 'install'], installFallback: null };
  }

  if (manager === 'yarn') {
    if (has('yarn.lock')) {
      return {
        install: ['yarn', 'install', '--frozen-lockfile'],
        installFallback: ['yarn', 'install'],
      };
    }

    return { install: ['yarn', 'install'], installFallback: null };
  }

  if (has('package-lock.json')) {
    return {
      install: ['npm', 'ci'],
      installFallback: ['npm', 'install'],
    };
  }

  return { install: ['npm', 'install'], installFallback: null };
}

/**
 * @param {{
 *   scripts?: Record<string, string>,
 *   dependencies?: Record<string, string>,
 *   devDependencies?: Record<string, string>,
 *   packageManager?: string,
 * }} pkg
 * @param {{
 *   script?: string,
 *   port?: string,
 *   lockfiles?: string[],
 *   userArgs?: string[],
 * }} [options]
 */
export function planProjectRun(pkg, options = {}) {
  const script = options.script || 'dev';
  const port = String(options.port || '5173');
  const lockfiles = (options.lockfiles || []).filter((name) => LOCKFILES.includes(name));
  const userArgs = options.userArgs || [];
  const deps = dependencyNames(pkg.dependencies, pkg.devDependencies);
  const scriptBody = pkg.scripts?.[script] || '';
  const declaredManager = packageManagerName(pkg.packageManager);

  let manager = 'npm';

  if (lockfiles.includes('pnpm-lock.yaml') || lockfiles.includes('pnpm-workspace.yaml')) {
    manager = 'pnpm';
  } else if (lockfiles.includes('yarn.lock')) {
    manager = 'yarn';
  } else if (declaredManager === 'pnpm' || declaredManager === 'yarn' || declaredManager === 'npm') {
    manager = declaredManager;
  }

  const { install, installFallback } = installCommands(manager, lockfiles);
  const extra = [...bindArgs(deps, scriptBody, port), ...userArgs];

  let run;

  if (manager === 'pnpm') {
    run = extra.length > 0 ? ['pnpm', 'run', script, '--', ...extra] : ['pnpm', 'run', script];
  } else if (manager === 'yarn') {
    run = ['yarn', script, ...extra];
  } else {
    run = extra.length > 0 ? ['npm', 'run', script, '--', ...extra] : ['npm', 'run', script];
  }

  return {
    manager,
    install,
    installFallback,
    run,
    script,
    port,
  };
}
